### PR TITLE
Control font related changes from SCSS variables

### PR DESCRIPTION
**Pull request by kaankabalak**
This commit also sets the default font to be Source Sans Pro to prevent
loading two separate fonts.

### CODE REVIEW

**Comment by deekoder** [comment]
@rushenn is there a way to drive the font selection from variables.scss.

**Comment by rushenn** [comment]
@deekoder We can add the font URL in `site.yml` as a parameter just like the logo. This way, we can avoid custom theme related edits on the main source files.

**Comment by rushenn** [comment]
@kaankabalak Do you wanna use Source Sans Pro as the default font of Gluegun or only for MinioHQ/Gluegun?

**Comment by kaankabalak** [comment]
If we aren't going to specify any fonts on `site.yml`, I thought setting Source Sans Pro as the default font of Gluegun might be a good solution

**Pull request merged**
