### PR TITLE
UI Enhancements

### PR DESCRIPTION
**Pull request by rushenn**
Fixes: https://github.com/minio/gluegun/issues/54 https://github.com/minio/gluegun/issues/53

### CODE REVIEW

**Comment by kaankabalak** [comment]
@deekoder, I think you need to have `gulp watch` running before you save any changes into the .scss file, you can then run the Gluegun commands to see the changes.

**Comment by rushenn** [comment]
@deekoder @kaankabalak 

- I have disabled the suggest edit button in mobile just like in the Doctor. I can enable it back if it's really necessary. 
- I don't see any functionalities for suggest edit in the codebase. May be you can address it in a different PR.
- You need to have `gulp watch` running before making any changes on scss and js files. `Gulp watch` is easier than something similar to `yarn build` when it comes to frequent changes so you don't need to build it every time when there is a minor change.  We can also have `build` task as a backup option.

**Comment by kaankabalak** [comment]
In terms of the functionality of the Suggest Edit button, I think we would need to redirect the users to the Github link of the document, just like in Doctor.

**Comment by deekoder** [comment]
oh right we dont need suggest edit in mobile we decided. It makes no sense in that form factor. So let leave that out. But i think we do need a build task. gulp watch is nice but its developer centric. So a devops or a non dev may not know how to do this. I will write a single makefile for everything then.

**Comment by deekoder** [comment]
Lets take this PR and then add build task and other things.

**Comment by harshavardhana** [comment]
Just like watch you can add `gulp build` task as well. For more references you can look at perhaps minio.io website code.

**Pull request merged**
