### PR TITLE
Enable backdrop click to hide sidebar

### PR DESCRIPTION
**Pull request by rushenn**
sidebar-backdrop

### CODE REVIEW

**Comment by kaankabalak** [comment]
When I hide the sidebar when the page width is larger than 1199px, and then decrease the page width, I can't hide the sidebar by clicking on the backdrop. I think this might be caused by the `body-locked` class not being added when I hide the sidebar on the wide view.

**Comment by deekoder** [comment]
for some reasons I can't see the css. Is the rake task broken?

**Comment by kaankabalak** [comment]
@deekoder That wasn't the case for me, I ran the `rake` command before running the other 3 commands that are listed on the readme and was able to see the CSS changes.

**Comment by deekoder** [comment]
@kaankabalak  do you approve?

**Pull request merged**
