### PR TITLE
Add intermediary ERB file to generate active sidebar classes

### PR DESCRIPTION
**Pull request by kaankabalak**
This commit improves page generation performance by generating the
sidebar once, including it in each page and handling active classes
based on the current page; as opposed to the sidebar being generated
with active classes by looping through the list of documents for each
page.

When the Gluegun commands are run, the _sidebar-template.erb file loops
through the list of documents once and generates the _sidebar.erb file
which contains the hardcoded sidebar with the conditionals that check
if the given sidebar item/category should have active classes. The
_sidebar.erb file is included on the beginning of the _header.erb file.

### CODE REVIEW

**Comment by deekoder** [comment]
One minor comment is the generate docs must be viewable locally without being hosted.

**Comment by rushenn** [comment]
@deekoder @kaankabalak Before the doc file generation process, I think it's better to remove the already generated 'doc' folder if exists in order to get rid of any leftover files which are not part of the current process.

**Comment by kaankabalak** [comment]
@deekoder, I will submit a fix for that issue shortly. 

@rushenn, I agree with you that we should remove the "doc" folder that is already generated before generating a new one, as I think that it is confusing for the users.

**Comment by kaankabalak** [comment]
@deekoder @rushenn Submitted fix for docs not being viewable locally on click and first link not being active on index.html when the slug for the first page wasn't entered, would appreciate if you could take another look.

**Pull request merged**
